name: Agent Analysis

on: [push, pull_request]

jobs:
  pucara-agent-job:
    runs-on: ubuntu-latest
    container: 
      image: public.ecr.aws/q3c8w0e5/agent-cvm:latest-amd64
    env:
      AWS_ACCESS_KEY_ID=${{vars.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY=${{vars.AWS_SECRET_ACCESS_KEY}}
      AGENT_TOOLS=trivy,codeql,semgrep
      AGENT_LANGUAGE=java
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Move project files
        run: mv $GITHUB_WORKSPACE/* /app

      - name: Run Analysis
        run: |
          echo "Running Analysis..."
          agent
